---
guid: 65de
ocp_template_dir: "{{ playbook_dir }}/ocp_template"
app_test_url: http://nodejs-mongo-persistent-smoke-test.apps.65de.example.opentlc.com

########## MULTITENANCY #######################

multitenant:
 nodes:
  - node: 
     name: node1.{{guid}}.internal
     label: aplha
  - node: 
     name: node2.{{guid}}.internal
     label: beta
  - node: 
     name: node3.{{guid}}.internal
     label: common
  - node: 
     name: node4.{{guid}}.internal
     label: common


## USERS ############################
users:
 - user:
    name: amy
    password: r3dh4t1!
    group: alpha
 - user:
    name: andrew
    password: r3dh4t1!
    group: alpha
 - user:
    name: brian
    password: r3dh4t1!
    group: beta
 - user:
    name: betty
    password: r3dh4t1!
    group: beta
 - user:
    name: admin
    password: admin
    group: poweruser


## PV TEMPLATE GENERATION ##################
pv_template:
  nfs_node: support1.65de.internal
  rwo:
    from: 1
    to: 25
    size: 5Gi
    mode: ReadWriteOnce
  rwx:
    from: 26
    to: 50
    size: 10Gi
    mode: ReadWriteMany


##- APPLIER -###########################################
## Applier for Cluster Content ###########################
applier:
  volumes:
   - object: PersistentVolume
     content:
      - name: PV creations for user
        file: "{{ playbook_dir }}/ocp_template/pvs/"

  smoketest:
   - object: projectRequest
     content:
      - name: smoke-test
        file: "{{ playbook_dir }}/ocp_template/smoketest/projectreq.yml"
        file_action: create

   - object: deployment
     content:
      - name: smoked-nodejs
        template: "{{ playbook_dir }}/ocp_template/smoketest/template/app-template.yml"
        params: "{{ playbook_dir }}/ocp_template/smoketest/param/smoke-param"
     #post-steps:
     # - role: /home/rfoe-redhat.com/ocp-ha-homework/lab/roles/smoked/tasks/main.yml

  app_pipeline:
   - object: projects
     content:
      - name: "create environments"
        file: "{{ playbook_dir }}/ocp_template/app_pipeline/template/projects.yml"
        file_action: create
   - object: deployments
     content:
      - name: "deploy jenkins environment"
        template: "{{ playbook_dir }}/ocp_template/app_pipeline/template/jenkins-persistent.yml"
        params: "{{playbook_dir}}/ocp_template/app_pipeline/param/jenkinsparam"
      - name: "deploy dev environment"
        template: "{{ playbook_dir }}/ocp_template/app_pipeline/template/deployment.yml"
        params: "{{playbook_dir}}/ocp_template/app_pipeline/param/deployment-dev"
      - name: "deply stage environment"
        template: "{{ playbook_dir }}/ocp_template/app_pipeline/template/deployment.yml"
        params: "{{playbook_dir}}/ocp_template/app_pipeline/param/deployment-stage"
      - name: "deply prod environment"
        template: "{{ playbook_dir }}/ocp_template/app_pipeline/template/deployment.yml"
        params: "{{playbook_dir}}/ocp_template/app_pipeline/param/deployment-prod"
   - object: hpa
     content:
      - name: "Set HPA"
        template: "{{ playbook_dir }}/ocp_template/app_pipeline/template/hpa.yml"
        params: "{{ playbook_dir }}/ocp_template/app_pipeline/param/hpa-prod"
   - object: builds
     content:
      - name: "deploy build pipeline to dev"
        template: "{{ playbook_dir }}/ocp_template/app_pipeline/template/build.yml"
        params: "{{ playbook_dir }}/ocp_template/app_pipeline/param/build-dev"

  proj_template:
   - object: projectTemplate
     content:
      - name: "Apply new Template"
        file: "{{playbook_dir}}/ocp_template/multitenant/template/project-req-template.yaml"