---
- name: Make sure Docker is running
  systemd: state=started name=docker enabled=yes

#- name: Make sure Docker is running on the right version 
#  shell: docker version|grep Version


- name: Add required repo
  command: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-ose-3.9-rpms" --enable="rhel-7-fast-datapath-rpms" --enable="rh-gluster-3-client-for-rhel-7-server-rpms" --enable="rhel-7-server-ansible-2.4-rpms" --enable="rhel-7-server-optional-rpms" --enable="rhel-7-server-rh-common-rpms" --enable="rhel-7-server-rpms"
