---
- name: required packages are present
  yum: name={{ item }} state=present
  with_items:
    - atomic-openshift-utils
    - atomic-openshift-clients
        
- name: Backup current host file
  copy: 
    src: /etc/ansible/hosts
    dest: ./original.hosts.backup

- name: Copy OpenShift install config
  template: src=ocphostconfig.j2 dest=/etc/ansible/hosts

# - name: Preparing Host files with Jinja
#   tasks:
#     - name: required packages are present
#       yum:
#         name:
#           - install atomic-openshift-utils
#           - atomic-openshift-clients
#         state: present



