---
# - name: Labelling the nodes
#   command: "oc label node {{item.node.name}} client={{item.node.label}} --overwrite"
#   with_items: '{{params.multitenant.nodes}}'
#   when: inventory_hostname_short == "localhost"


# - name: Labelling the nodes
#   command: "oc create -f {{playbook_dir}}/ocp_template/multitenant/template/project-req-template.yaml -n default"
#   when: inventory_hostname_short == "localhost"


# - name: Modify master yaml files to reflect latest project template
#   lineinfile: 
#    path: /etc/origin/master/master-config.yaml
#    regexp: "projectRequestTemplate:"
#    line: "  projectRequestTemplate: 'default/custom-project-request'"
#   when: "'masters' in group_names"

# - name: Modify master yaml files to reflect latest project template
#   lineinfile: 
#    path: /etc/origin/master/master-config.yaml
#    regexp: "defaultNodeSelector:"
#    line: "  defaultNodeSelector: 'env=app,client=common'"
#   when: "'masters' in group_names"

## TODO :: start from here , try to figure out what is going on..... 
- name: Modify master yaml files to position pod placement by project
  lineinfile: 
  #  path: /etc/origin/master/master-config.yaml
   path: /home/rfoe-redhat.com/test/test2.yaml
   regexp: "{{item.regex}}"
   insertafter: "{{item.regex}}"
   line: "{{item.line}}"
  with_items: 
   - {regex: "pluginConfig:", line: "  PodNodeSelector:" }
  #  - {regex: "PodNodeSelector:", line: "  configuration:" }
  #  - {regex: "configuration:", line: "  podNodeSelectorPluginConfig:" }
  #  - {regex: "podNodeSelectorPluginConfig:", line: "  clusterDefaultNodeSelector:" }
  #  - {regex: "clusterDefaultNodeSelector:", line: "  alpha-corp:client=alpha" }
  #  - {regex: "alpha-corp:", line: "  beta-corp:client=beta" }
  when: inventory_hostname_short == "localhost"


# - name: Restart Openshift Master
#   command: "systemctl restart atomic-openshift-master-api atomic-openshift-master-controllers"
#   when: "'masters' in group_names"


#TODO :: pod node selector..... 
#need to create admission files

# systemctl restart atomic-openshift-master
## configure node selector 


# - name: Apply new project template
#   import_role:
#     name: openshift-applier
#   vars:
#     openshift_cluster_content: "{{params.applier.proj_template}}"
#   when: "inventory_hostname == 'localhost'"