---

- name: Generate user in htpasswd
  htpasswd:
   path: /etc/origin/master/htpasswd
   name: '{{ item.user.name }}'
   password: '{{ item.user.password }}'
  with_items: '{{ params.users }}'
  when: "'masters' in group_names"


- name: Labelling the nodes
  command: "oc label node {{item.node.name}} client={{item.node.label}} --overwrite"
  with_items: '{{params.multitenant.nodes}}'
  when: inventory_hostname_short == "localhost"


- name: Labelling the nodes
  command: "oc create -f {{playbook_dir}}/ocp_template/multitenant/template/project-req-template.yaml -n default"
  when: inventory_hostname_short == "localhost"


- name: Modify master yaml files to reflect latest project template
  lineinfile: 
   path: /etc/origin/master/master-config.yaml
   regexp: "projectRequestTemplate:"
   line: "  projectRequestTemplate: 'default/custom-project-request'"
  when: "'masters' in group_names"

# - name: Modify master yaml files to reflect latest project template
#   lineinfile: 
#    path: /etc/origin/master/master-config.yaml
#    regexp: "defaultNodeSelector:"
#    line: "  defaultNodeSelector: 'env=app,client=common'"
#   when: "'masters' in group_names"

- name: Modify master yaml files to position pod placement by project
  lineinfile: 
   path: /etc/origin/master/master-config.yaml
   insertafter: "{{item.regex}}"
   line: "{{item.line}}"
  with_items: 
   - {regex: "pluginConfig:", line: "    PodNodeSelector:" }
   - {regex: "PodNodeSelector:", line: "     configuration:\n      podNodeSelectorPluginConfig:" }
   - {regex: "podNodeSelectorPluginConfig:", line: "       clusterDefaultNodeSelector: 'env=app,client=common'" }
   - {regex: "clusterDefaultNodeSelector: 'env=app,client=common'", line: "       corp-alpha: 'env=app,client=alpha'" }
   - {regex: "corp-alpha: 'env=app,client=alpha'", line: "       corp-beta: 'env=app,client=beta'" }
  when: "'masters' in group_names"



- name: Restart Openshift Master
  command: "systemctl restart atomic-openshift-master-api atomic-openshift-master-controllers"
  when: "'masters' in group_names"


#TODO :: pod node selector..... 
## Create projects 
# oc adm new-project corp-alpha --node-selector='client=alpha'
# oc patch namespace corp-alpha -p '{"metadata":{"annotations":{"scheduler.alpha.kubernetes.io/node-selector":"client=alpha"}}}'
# oc adm groups new corpalpha andrew amy
# oc adm policy add-role-to-group admin corpalpha -n corp-alpha


# oc adm new-project corp-beta --node-selector='client=beta'
# oc patch namespace corp-beta -p '{"metadata":{"annotations":{"scheduler.alpha.kubernetes.io/node-selector":"client=beta"}}}'
# oc adm groups new corpalpha bryan betty
# oc adm policy add-role-to-group admin corpbeta -n corp-beta

## END 

#need to create admission files
# systemctl restart atomic-openshift-master
## configure node selector 


# - name: Apply new project template
#   import_role:
#     name: openshift-applier
#   vars:
#     openshift_cluster_content: "{{params.applier.proj_template}}"
#   when: "inventory_hostname == 'localhost'"