---
- name: Labelling the nodes
  command: "oc label node {{item.node.name}} client={{item.node.label}} --overwrite"
  with_items: '{{tenantlabels.nodes}}'
  when: inventory_hostname_short == "localhost"


- name: Create new project req template
  command: "oc create -f {{playbook_dir}}/ocp_template/multitenant/template/project-req-template.yaml -n default"
  when: inventory_hostname_short == "localhost"


- name: Modify master yaml files to reflect latest project template
  lineinfile: 
   path: /etc/origin/master/master-config.yaml
   regexp: "projectRequestTemplate:"
   line: "  projectRequestTemplate: 'default/project-request'"
  when: "'masters' in group_names"

- name: Modify master yaml files to position pod placement by project
  lineinfile: 
   path: /etc/origin/master/master-config.yaml
   insertafter: "{{item.regex}}"
   line: "{{item.line}}"
  with_items: 
   - {regex: "pluginConfig:", line: "    PodNodeSelector:" }
   - {regex: "PodNodeSelector:", line: "     configuration:\n      podNodeSelectorPluginConfig:" }
   - {regex: "podNodeSelectorPluginConfig:", line: "       clusterDefaultNodeSelector: 'env=app,client=common'" }
   - {regex: "clusterDefaultNodeSelector: 'env=app,client=common'", line: "       corp-alpha: 'env=app,client=alpha'" }
   - {regex: "corp-alpha: 'env=app,client=alpha'", line: "       corp-beta: 'env=app,client=beta'" }
  when: "'masters' in group_names"



- name: Restart Openshift Master
  command: "systemctl restart atomic-openshift-master-api atomic-openshift-master-controllers"
  when: "'masters' in group_names"


- name: Generate user in htpasswd
  htpasswd:
   path: /etc/origin/master/htpasswd
   name: '{{item.user.name}}'
   password: '{{item.user.password}}'
  with_items: '{{params.users }}'
  when: "'masters' in group_names"

- name: Create Project for Alpha and Beta
  command: "{{item}}"
  with_items:
   - oc adm new-project corp-alpha --node-selector='client=alpha'
   - oc patch namespace corp-alpha -p '{"metadata":{"annotations":{"scheduler.alpha.kubernetes.io/node-selector":"client=alpha"}}}'
   - oc adm new-project corp-beta --node-selector='client=beta'
   - oc patch namespace corp-beta -p '{"metadata":{"annotations":{"scheduler.alpha.kubernetes.io/node-selector":"client=beta"}}}'
  when: inventory_hostname_short == "localhost"

- name: Define User role and Group
  command: "{{item}}"
  with_items:
   - "oc adm policy add-cluster-role-to-user cluster-admin admin"
   - "oc adm groups new corpalpha andrew amy"
   - "oc adm groups new corpbeta bryan betty"
   - oc adm policy add-role-to-group admin corpalpha -n corp-alpha
   - oc adm policy add-role-to-group admin corpbeta -n corp-beta
  when: inventory_hostname_short == "localhost"